sudo: required
dist: trusty

services:
  - docker

language: cpp

# command to run tests
script:
  - shopt -s extglob dotglob
  - mkdir Package
  - mv !(Package) Package
  - shopt -u dotglob
  - export PKGDIR=${PWD}/Package
  - docker run -it --name CI_container -v $PKGDIR:/Package -e GITHUB_TOKEN=$GITHUB_TOKEN -d rete/marlinmt-ci
  - docker exec -it CI_container /bin/bash -c "/Package/.travis-ci.d/compile_and_test.sh"

# deploy mkdocs documentation
after_success:
  - if [[ "${TRAVIS_EVENT_TYPE}" != "cron" && "${TRAVIS_EVENT_TYPE}" != "pull_request" && "${TRAVIS_REPO_SLUG%/*}" == "iLCSoft" && -z ${TRAVIS_TAG} ]];
    then docker exec -it CI_container /bin/bash -c "/Package/.travis-ci.d/deploy_documentation.sh";
    fi

# Don't send e-mail notifications
notifications:
  email:
    on_success: never
    on_failure: always
