sudo: required
dist: trusty

services:
  - docker

language: cpp

before_install:
  - sudo apt-get -y install python-pip
  - sudo pip install --upgrade pip

install:
  - sudo pip install mkdocs mkdocs-material pymdown-extensions pygments
  - git clone https://github.com/pieterdavid/mkdocs-doxygen-plugin.git
  - cd mkdocs-doxygen-plugin
  - python setup.py install --user
  - cd ..

# command to run tests
script:
  - shopt -s extglob dotglob
  - mkdir Package
  - mv !(Package) Package
  - shopt -u dotglob
  - export PKGDIR=${PWD}/Package
  - docker run -it --name CI_container -v $PKGDIR:/Package -d rete/marlinmt-ci
  - docker exec -it CI_container /bin/bash -c "/Package/.travis-ci.d/compile_and_test.sh"

# deploy mkdocs documentation
on_success:
  - if [[ "${TRAVIS_EVENT_TYPE}" != "cron" && "${TRAVIS_EVENT_TYPE}" != "pull_request" && "${TRAVIS_REPO_SLUG%/*}" == "iLCSoft" && -z ${TRAVIS_TAG} ]];
    then cd Package; git remote rm origin; git remote add origin https://rete:$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG.git; docker exec -it CI_container -w /Package /bin/bash -c "mkdocs gh-deploy";
    fi

# Don't send e-mail notifications
notifications:
  email:
    on_success: never
    on_failure: always
